import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function renderFromResult() {
  try {
    // 1. Read the JSON generated by generatePostFromTheme.js
    const jsonPath = path.join(__dirname, 'result.json');
    const jsonRaw = await fs.readFile(jsonPath, 'utf-8');
    const postData = JSON.parse(jsonRaw);

    // 2. Read the HTML template
    const templatePath = path.join(__dirname, 'src', 'templates', 'post.html');
    let template = await fs.readFile(templatePath, 'utf-8');

    // 3. Read the CSS for inlining (optional but good for performance)
    const cssPath = path.join(__dirname, 'src', 'templates', 'theme-neon.css');
    const cssContent = await fs.readFile(cssPath, 'utf-8');
    
    // Replace the external link with inline CSS
    template = template.replace(
      '<link rel="stylesheet" href="theme-neon.css">',
      `<style>\n${cssContent}\n</style>`
    );

    // 4. Build Sections HTML (Merging Summary, Bible Passage, Practical Example)
    const sectionsHTML = `
        <h2 class="neon-purple">Resumo</h2>
        <p>${postData.summary}</p>
        
        <h2 class="neon-purple">Recomendação de Estudo</h2>
        <div class="book-card" style="display:flex; gap:20px; margin:20px 0; padding:20px; background:rgba(255,255,255,0.05); border-radius:12px; border:1px solid rgba(139,92,246,0.3);">
            <img src="${postData.recommendedBook.coverUrl}" alt="Capa de ${postData.recommendedBook.title}" style="max-width:120px; border-radius:8px;">
            <div>
                <h3>${postData.recommendedBook.title}</h3>
                <a href="${postData.recommendedBook.pageUrl}" class="action-btn" style="display:inline-block; margin-top:10px; padding:8px 16px; background:var(--primary); color:#fff; text-decoration:none; border-radius:6px; font-weight:bold;">Acessar Estudo Completo</a>
            </div>
        </div>

        <h2 class="neon-purple">A Palavra</h2>
        <blockquote class="bible-verse">
            <span class="quote-mark">“</span>
            ${postData.biblicalPassage.text}
            <footer>— ${postData.biblicalPassage.reference}</footer>
        </blockquote>

        <h2 class="neon-purple">Aplicação Prática</h2>
        <p>${postData.practicalExample}</p>
    `;

    // 5. Replace Placeholders
    const placeholders = {
      '{{TITLE}}': postData.topic,
      '{{META_DESC}}': postData.summary.substring(0, 150) + '...',
      '{{COVER_URL}}': postData.recommendedBook.coverUrl || 'assets/default-cover.jpg',
      '{{COVER_ALT}}': `Estudo Bíblico sobre ${postData.topic}`,
      '{{PAGE_URL}}': `https://rumoanovajerusalem.github.io/blogger_Estudos/post-${slugify(postData.topic)}.html`,
      '{{LOGO_URL}}': 'https://rumoanovajerusalem.github.io/blogger_Estudos/assets/images/logo.png', // Fallback
      '{{DATE}}': new Date().toISOString(),
      '{{FORMATTED_DATE}}': new Date().toLocaleDateString('pt-BR'),
      '{{INTRO}}': `<p>Bem-vindo ao estudo sobre <strong>${postData.topic}</strong>. Este material foi cuidadosamente preparado pela IA com base em nossos estudos cristãos.</p>`,
      '{{SECTIONS_HTML}}': sectionsHTML,
      '{{CONCLUSION}}': `Esperamos que esta reflexão baseada no livro <em>${postData.recommendedBook.title}</em> tenha abençoado sua vida.`,
      '{{MAP_DATA_JSON}}': JSON.stringify(buildMapData(postData)),
      '{{PREV_URL}}': 'index.html',
      '{{NEXT_URL}}': 'index.html',
      // Clean up WebP/AVIF if not heavily used
      '<source srcset="{{COVER_URL_AVIF}}" type="image/avif">': '',
      '<source srcset="{{COVER_URL_WEBP}}" type="image/webp">': ''
    };

    let resultHTML = template;
    for (const [key, val] of Object.entries(placeholders)) {
      resultHTML = resultHTML.replaceAll(key, val);
    }

    // 6. Write Final File
    const slug = slugify(postData.topic);
    const outPath = path.join(__dirname, `post-${slug}.html`);
    await fs.writeFile(outPath, resultHTML, 'utf-8');
    
    console.log(`✅ Sucesso! Post gerado e salvo em: post-${slug}.html`);

  } catch (err) {
    console.error('❌ Erro no renderFromResult:', err.message);
    process.exit(1);
  }
}

function slugify(text) {
  return text.toString().toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // remove accents
    .replace(/\s+/g, '-')           // Replace spaces with -
    .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
    .replace(/\-\-+/g, '-')         // Replace multiple - with single -
    .replace(/^-+/, '')             // Trim - from start of text
    .replace(/-+$/, '');            // Trim - from end of text
}

function buildMapData(postData) {
    return {
        center: postData.topic,
        branches: [
            { label: 'Referência', ref: postData.biblicalPassage.reference },
            { label: 'Livro Base', ref: postData.recommendedBook.title },
            { label: 'Ação Prática', ref: "Ver conteúdo" }
        ]
    };
}

// Execute
renderFromResult();
